apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumption-netsms-serviceusagesbroadbands-v1-deployment
spec:
  selector:
    matchLabels:
      component: consumption-netsms-serviceusagesbroadbands-v1-pod
  strategy:
    type: RollingUpdate
    rollingUpdate: #Update Pods a certain number at a time
      maxUnavailable: 1 #Total number of pods that can be unavailable at once
      maxSurge: 1 #Maximum number of pods that can be deployed above desired state
  replicas: 2
  template:
    metadata:
      labels:
        component: consumption-netsms-serviceusagesbroadbands-v1-pod
    spec:
      #serviceAccountName: service-orch-ordermanagement-svc-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
      containers:
        - name: consumption-netsms-serviceusagesbroadbands-v1-container
          image: harbor.prod.lpa.k8s.corp.clarobr/modernizacao-soa/consumption-netsms-serviceusagesbroadbands-v1-img
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources: # QoS Guaranteed limit e request iguais
            limits:
              cpu: 200m       # Limite de CPU (vCPU)
              memory: 200Mi   # Limite de memória
            requests:
              cpu: 200m       # Solicitação de CPU
              memory: 200Mi   # Solicitação de memória
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: consumption-netsms-serviceusagesbroadbands-v1-config-map
            - secretRef:
                name: consumption-netsms-serviceusagesbroadbands-v1-secret
          volumeMounts:
            - name: consumption-netsms-serviceusagesbroadbands-config-map-volume
              mountPath: "/home/serviceusagesbroadbandsv1-user/configs"
            - name: consumption-netsms-serviceusagesbroadbands-secret-volume
              mountPath: "/home/serviceusagesbroadbandsv1-user/secrets"
              readOnly: true
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            successThreshold: 1
            failureThreshold: 7
            periodSeconds: 10
            timeoutSeconds: 10
      imagePullSecrets:
        - name: harbor
      volumes:
        - name: consumption-netsms-serviceusagesbroadbands-config-map-volume
          projected:
            sources:
              - configMap:
                  name: consumption-netsms-serviceusagesbroadbands-v1-config-map
        - name: consumption-netsms-serviceusagesbroadbands-secret-volume
          projected:
            sources:
              - secret:
                  name: consumption-netsms-serviceusagesbroadbands-v1-secret

