apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: consumption-netsms-serviceusagesbroadbands-v1
  env: ${KUBERNETES_CONTEXT}
  owner: consumption-netsms-serviceusagesbroadbands-v1
commonAnnotations:
  author: "Gabriel Joioso"
  email: "g.eduardojoioso2@dxc.com"
  company: "Claro BR"
  revision: "${GIT_COMMIT_FORMATTED}"
  version: ${POM_VERSION}
images:
  - name: ${HARBOR_HOST}/${HARBOR_REPO}/consumption-netsms-serviceusagesbroadbands-v1-img
    newName: "${DEPLOY_IMAGE_CONSUMPTION_NETSMS_SERVICEUSAGESBROADBANDS_V1}"
    newTag: "${DEPLOY_IMAGE_TAG}"
bases:
  - ../../base
resources:
#substituir o nome dos arquivos abaixo pelo nome dos arquivos na pasta
  - consumption-netsms-serviceusagesbroadbands-v1-config-map.yaml
  - consumption-netsms-serviceusagesbroadbands-v1-secret.yaml
  - consumption-netsms-serviceusagesbroadbands-v1-ingress.yaml
  - consumption-netsms-serviceusagesbroadbands-v1-hpa.yaml
patchesStrategicMerge: 
  - consumption-netsms-serviceusagesbroadbands-v1-deployment.yaml